Content+
TimoliaDE/HowTo pull request #118
Opened 2024-12-03 20:00 UTC by Schneeeulen

2024-12-03 20:19 UTC, q8hTimolia approved these changes

2024-12-03 21:52 UTC, byRoadrunner requested changes
Please don't simply rename the old rank images, just delete them, as we have the history anyways which is stored in the git commits.

2024-12-04 06:09 UTC, Schneeeulen commented
Removed Old Images

2024-12-05 16:49 UTC, D4rkulus approved these changes

2024-12-05 16:49 UTC, merged