Ins Englische übersetzt
TimoliaDE/HowTo pull request #25
Opened 2023-08-30 20:01 UTC by Schneeeulen

2023-08-30 20:12 UTC, FieryFigure commented on docs/games/splun.en.md
> +- Try to stay a live as long as possible with jumping from block to block.
a live -> alive

2023-08-30 20:23 UTC, FieryFigure requested changes
Bitte noch angemerkte Sachen ändern

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +- Vote with `/vote <Map>` or with a klick into the Chat for the Map of your choise.
choise -> choice

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +- Try to stay a live as long as possible with jumping from block to block.
a live -> alive

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +- <strong>Rocket</strong>: You can spring higher.
spring -> jump

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +- <strong>Feather</strong>: Your not going to destroy blocks.
Your -> you're

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +- All you will touch is going to despawn under your foots.
foots -> feet

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +- Map votes of players with a premium rank count more.
"Map votes of players with a premium rank count for up to four votes"

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +Detailed infos about our ranks and their benefits are listed [hier](/ranks/premium/).
hier -> here

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
> +If you like BrainBow and wanna get creative you can show us your own BrainBow map by creating a new one. Maps can be submitted in our [Discord](https://timolia.de/discord).
BrainBow? Lieber komplett raus nehmen.

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
>  | Rang | Punkte | Name |
Übersetzen

2023-08-30 20:23 UTC, FieryFigure commented on docs/games/splun.en.md
>  | 5 | 1024 | Grashüpfer |
Die drei Ränge auch übersetzen!

2023-09-16 00:55 UTC, l3nnartt commented on docs/games/splun.en.md
>  | 5 | 1024 | Grashüpfer |
Ne, die heißen Ingame ja auch so auf Deutsch, denke das muss nicht.

2023-10-29 19:24 UTC, Schneeeulen commented
> Bitte noch angemerkte Sachen ändern

Geändert

2023-10-29 20:09 UTC, q8hTimolia commented on docs/games/splun.en.md
> +- Vote with `/vote <Map>` or with a klick into the Chat for the Map of your choice.
klick -> click

2023-10-29 20:10 UTC, q8hTimolia commented on docs/games/splun.en.md
> +- <strong>Stone</strong>: A levitation platform is forming beneath your feet.
levitation -> levitating

2023-10-29 20:11 UTC, q8hTimolia commented on docs/games/splun.en.md
> +- <strong>Trank</strong>: Fill your opponents with arrows (Nausea effect).
Trank - Potion

2023-12-19 14:09 UTC, Schneeeulen reviewed
should be accepted

2023-12-19 15:09 UTC, q8hTimolia approved these changes

2023-12-20 11:12 UTC, l3nnartt approved these changes

2023-12-20 11:12 UTC, merged

2023-12-20 11:13 UTC, l3nnartt commented
thx u