Freebuild
TimoliaDE/HowTo pull request #32
Opened 2023-09-17 18:46 UTC by Schneeeulen

Freebuild Command-List (de+en) and Freebuild Rules (de+en)

2023-09-18 13:42 UTC, l3nnartt requested changes

2023-09-18 13:42 UTC, l3nnartt commented on docs/commands.de.md
> +| `/claim` | Beansprucht den Chunk in welchem du dich befindest |
die commands bitte alphabetisch sortieren

2023-09-18 13:42 UTC, l3nnartt commented on docs/commands.en.md
> +| `/claim` | Claim the chunk you're in |
hier auch

2023-09-18 15:13 UTC, Schneeeulen commented on docs/commands.de.md
> +| `/claim` | Beansprucht den Chunk in welchem du dich befindest |
Erledigt

2023-09-18 15:13 UTC, Schneeeulen commented on docs/commands.en.md
> +| `/claim` | Claim the chunk you're in |
Erledigt

2023-09-25 14:55 UTC, q8hTimolia approved these changes

2023-09-28 12:24 UTC, l3nnartt commented on docs/rules/freebuild.en.md
> +Last updated: Septembre 17, 2023
denke das hier ist noch ein kleiner Schreibfehler?

2023-09-28 13:33 UTC, Schneeeulen commented on docs/rules/freebuild.en.md
> +Last updated: Septembre 17, 2023
ja, die klassischen zeichenfehler. Danke :)

2023-09-28 23:04 UTC, merged