Removed Mareeeek
TimoliaDE/HowTo pull request #34
Opened 2023-10-22 12:06 UTC by Schneeeulen

2023-10-22 15:47 UTC, l3nnartt requested changes
the responsibilities should also be removed

2023-10-22 16:46 UTC, Schneeeulen commented
Ok, thanks. Changed

2023-10-22 20:20 UTC, l3nnartt approved these changes

2023-10-27 17:28 UTC, q8hTimolia approved these changes

2023-10-27 17:28 UTC, merged