Update Zuständigkeiten
TimoliaDE/HowTo pull request #52
Opened 2023-12-21 22:12 UTC by ALetsPlayYT

2023-12-21 22:15 UTC, q8hTimolia approved these changes

2023-12-21 22:16 UTC, DevMoritz approved these changes

2023-12-21 22:35 UTC, l3nnartt requested changes
bitte nochmal die alphabetische Sortierung checken

2023-12-22 09:10 UTC, SplotyCode commented
Wenn das alphabetisch sein soll, kann man auch ein sort beim generieren machen

2023-12-22 09:54 UTC, Schneeeulen approved these changes

2024-01-02 09:04 UTC, merged

2024-01-02 09:45 UTC, l3nnartt commented
> Wenn das alphabetisch sein soll, kann man auch ein sort beim generieren machen

langfristig sicher sinnvoll